                fancyindex_default_sort size;
                fancyindex_name_length 255;
                fancyindex_case_sensitive on;
                fancyindex_directories_first off;

                fancyindex_css_href "/main.css";
                fancyindex_header "/header.html";
                fancyindex_footer "/footer.html";

                fancyindex_show_path on;
                fancyindex_show_dotfiles off;
                fancyindex_ignore fix_mp3_filenames.sh fix_flac_filenames.sh fix_wav_filenames.sh mp3.tags.json flac.tags.json wav.tags>
                #"!([abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789\-\_\.]{2,256}(\.flac|\.mp3|\.wav|\.pdf){1})";
                fancyindex_hide_symlinks off;
                fancyindex_hide_parent_dir on;
                fancyindex_localtime on;
                fancyindex_time_format "%a %e %B @ %T";
                set $onelink onelink;
